site_name: Do It Yourself Seeing Monitor
site_url: http://localhost:8000/
theme:
  name: readthedocs
  highlightjs: true

plugins:
  - search
  - panzoom:
      always_show_hint: true 
      include_selectors:
        - "img" 

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
    - footnotes